/**
 * M1 (FR-023): cross-language conformance. deriveFlow's resolved paths must
 * match the fixture generated by aieos-governance-foundation from the real
 * kit-manifest.yml + artifact-file convention — the same JSON the Python
 * suite asserts against, so a convention change cannot drift one deriver.
 *
 * Locates the gf checkout via AIEOS_GF_PATH, then ../aieos-governance-foundation
 * (CI sibling checkout and local dev layout); skips when absent.
 */
import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { parse as parseYaml } from 'yaml';
import { deriveFlow } from '../derive-flow.js';
import { ManifestService } from '../manifest-service.js';

interface FixtureArtifact {
  id: string;
  token: string;
  human_authored: boolean;
  files: Record<string, string>;
  output: string;
}

function findGf(): string | null {
  // vitest runs with cwd = repo root (same convention as the fake-harness
  // subprocess test); the console is ESM, so no __dirname here.
  const candidates = [
    process.env.AIEOS_GF_PATH,
    path.resolve('aieos-governance-foundation'),
    path.resolve('..', 'aieos-governance-foundation'),
  ].filter((c): c is string => Boolean(c));
  for (const c of candidates) {
    if (fs.existsSync(path.join(c, 'kit-manifest.yml'))) {
      return c;
    }
  }
  return null;
}

const GF = findGf();
const FIXTURE = GF
  ? path.join(GF, 'tests', 'fixtures', 'convention', 'expected-files.json')
  : null;

describe.skipIf(!GF || !fs.existsSync(FIXTURE as string))(
  'deriveFlow conformance against the gf convention fixture',
  () => {
    it('resolves every artifact of every kit exactly as the fixture declares', () => {
      const fixture = JSON.parse(
        fs.readFileSync(FIXTURE as string, 'utf-8'),
      ) as {
        kits: Record<
          string,
          { repository: string; artifacts: FixtureArtifact[] }
        >;
      };

      const svc = new ManifestService({
        manifestPath: path.join(GF as string, 'kit-manifest.yml'),
        kitRoot: path.dirname(GF as string),
      });
      const manifest = svc.loadManifest();

      // yaml parse sanity: same file the fixture was generated from
      expect(parseYaml(fs.readFileSync(path.join(GF as string, 'kit-manifest.yml'), 'utf-8'))).toBeTruthy();

      let checked = 0;
      for (const [abbr, kitFixture] of Object.entries(fixture.kits)) {
        const flow = deriveFlow(abbr, manifest);
        const stepsByPrefix = new Map(
          flow.steps.map((s) => [s.produces.artifactIdPrefix, s]),
        );
        for (const art of kitFixture.artifacts) {
          const step = stepsByPrefix.get(art.id);
          if (!step) {
            // fixture covers artifacts[]; deriveFlow drives artifact_flow —
            // every flow entry must match, extras in artifacts[] are fine
            continue;
          }
          expect(step.fourFiles.spec, `${abbr}/${art.id} spec`).toBe(
            art.files.spec,
          );
          expect(step.fourFiles.template, `${abbr}/${art.id} template`).toBe(
            art.files.template,
          );
          expect(step.fourFiles.validator, `${abbr}/${art.id} validator`).toBe(
            art.files.validator,
          );
          expect(
            step.fourFiles.prompt,
            `${abbr}/${art.id} prompt`,
          ).toBe(art.files.prompt ?? null);
          expect(
            `docs/sdlc/${step.produces.outputFilename}`,
            `${abbr}/${art.id} output`,
          ).toBe(art.output);
          checked += 1;
        }
      }
      expect(checked).toBeGreaterThanOrEqual(60);
    });
  },
);
